<a href="https://colab.research.google.com/github/abhinivesh-s/Semi-Supervised-Text/blob/main/Running_MixText_v5_ISIS_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# memory footprint support libraries/code
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
gpu = GPUs[0]
def printm():
 process = psutil.Process(os.getpid())
 print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
 print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
printm()

  Created wheel for gputil: filename=GPUtil-1.4.0-cp37-none-any.whl size=7411 sha256=49e1a4923d04808fa50844860874ae6ded984f8b97b2fb8650270636b0551451
  Stored in directory: /root/.cache/pip/wheels/3d/77/07/80562de4bb0786e5ea186911a2c831fdd0018bda69beab71fd
Successfully built gputil
Gen RAM Free: 26.3 GB  | Proc size: 118.3 MB
GPU RAM Free: 16280MB | Used: 0MB | Util   0% | Total 16280MB


In [ ]:
import torch
torch.cuda.get_device_name()

'Tesla P100-PCIE-16GB'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd "/content/drive/My Drive/Colab Notebooks/MixText-master"

/content/drive/My Drive/Colab Notebooks/MixText-master


In [ ]:
!ls

 code   LICENSE    'Running MixText v3.ipynb'
 data   README.md  'Running MixText v4 ISIS Data.ipynb'


In [ ]:
!pip install pytorch-transformers

     |████████████████████████████████| 184kB 4.0MB/s 
     |████████████████████████████████| 133kB 31.2MB/s 
     |████████████████████████████████| 901kB 25.7MB/s 
     |████████████████████████████████| 1.2MB 26.7MB/s 
     |████████████████████████████████| 81kB 8.8MB/s 
     |████████████████████████████████| 7.5MB 29.6MB/s 
ERROR: botocore 1.20.72 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 1.24.3 which is incompatible.


In [ ]:
!python ./code/normal_train.py --gpu 0,1 --n-labeled 10 --data-path ./data/isis_twitter/ \
--batch-size 8 --epochs 6 

gpu num:  1
We entered get_data
100% 231508/231508 [00:00<00:00, 1919187.69B/s]
Read data successful (98007, 2) (42004, 2) n_labeled =  10
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attacks-Iraq-Bangladesh-following-Islamists-call-slaughtering-Ramadan.html pic.twitter.com/O0UCPPnyjL'
 'RT @AfarinMamosta: ISIS terrorists sent to hell,

In [ ]:
!python ./code/normal_train.py --gpu 0,1 --n-labeled 200 --data-path ./data/isis_twitter/ \
--batch-size 8 --epochs 6

gpu num:  1
We entered get_data
Read data successful (98007, 2) (42004, 2) n_labeled =  200
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attacks-Iraq-Bangladesh-following-Islamists-call-slaughtering-Ramadan.html pic.twitter.com/O0UCPPnyjL'
 'RT @AfarinMamosta: ISIS terrorists sent to hell, south of #Manbij pic.twitter.com/OsMEdIJKwi']


In [ ]:
!python ./code/normal_train.py --gpu 0,1 --n-labeled 1000 --data-path ./data/isis_twitter/ \
--batch-size 8 --epochs 6

gpu num:  1
We entered get_data
Read data successful (98007, 2) (42004, 2) n_labeled =  1000
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attacks-Iraq-Bangladesh-following-Islamists-call-slaughtering-Ramadan.html pic.twitter.com/O0UCPPnyjL'
 'RT @AfarinMamosta: ISIS terrorists sent to hell, south of #Manbij pic.twitter.com/OsMEdIJKwi']

In [ ]:
!python ./code/normal_train.py --gpu 0,1 --n-labeled 2400 --data-path ./data/isis_twitter/ \
--batch-size 8 --epochs 6

gpu num:  1
We entered get_data
Read data successful (98007, 2) (42004, 2) n_labeled =  2400
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attacks-Iraq-Bangladesh-following-Islamists-call-slaughtering-Ramadan.html pic.twitter.com/O0UCPPnyjL'
 'RT @AfarinMamosta: ISIS terrorists sent to hell, south of #Manbij pic.twitter.com/OsMEdIJKwi']

In [ ]:
#n_unlabeled = 5000

!python ./code/train.py --gpu 0,1,2,3 --n-labeled 10 \
--data-path ./data/isis_twitter/ --batch-size 8 --batch-size-u 1 --epochs 6 --val-iteration 100 \
--lambda-u 1 --T 1 --alpha 16 --mix-layers-set 7 9 12 \
--lrmain 0.000005 --lrlast 0.0005

2021-05-13 10:49:26.191175: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
GPU num:  1
Whether mix:  True
Mix layers sets:  [7, 9, 12]
We entered get_data
100% 231508/231508 [00:00<00:00, 2881657.77B/s]
Read data successful (98007, 2) (42004, 2) n_labeled =  10
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-

In [ ]:
#n_unlabeled = 5000

!python ./code/train.py --gpu 0,1,2,3 --n-labeled 200 \
--data-path ./data/isis_twitter/ --batch-size 8 --batch-size-u 1 --epochs 6 --val-iteration 100 \
--lambda-u 1 --T 1 --alpha 16 --mix-layers-set 7 9 12 \
--lrmain 0.000005 --lrlast 0.0005

2021-05-13 11:19:03.070379: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
GPU num:  1
Whether mix:  True
Mix layers sets:  [7, 9, 12]
We entered get_data
Read data successful (98007, 2) (42004, 2) n_labeled =  200
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attack

In [ ]:
#n_unlabeled = 5000

!python ./code/train.py --gpu 0,1,2,3 --n-labeled 1000 \
--data-path ./data/isis_twitter/ --batch-size 8 --batch-size-u 1 --epochs 6 --val-iteration 100 \
--lambda-u 1 --T 1 --alpha 16 --mix-layers-set 7 9 12 \
--lrmain 0.000005 --lrlast 0.0005

2021-05-13 11:55:26.242220: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
GPU num:  1
Whether mix:  True
Mix layers sets:  [7, 9, 12]
We entered get_data
Read data successful (98007, 2) (42004, 2) n_labeled =  1000
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attac

In [ ]:
#n_unlabeled = 5000

!python ./code/train.py --gpu 0,1,2,3 --n-labeled 2400 \
--data-path ./data/isis_twitter/ --batch-size 8 --batch-size-u 1 --epochs 6 --val-iteration 100 \
--lambda-u 1 --T 1 --alpha 16 --mix-layers-set 7 9 12 \
--lrmain 0.000005 --lrlast 0.0005

2021-05-13 12:44:21.550581: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
GPU num:  1
Whether mix:  True
Mix layers sets:  [7, 9, 12]
We entered get_data
Read data successful (98007, 2) (42004, 2) n_labeled =  2400
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attac

In [ ]:
#n_unlabeled = 5000

!python ./code/train.py --gpu 0,1,2,3 --n-labeled 2400 \
--data-path ./data/isis_twitter/ --batch-size 8 --batch-size-u 1 --epochs 20 --val-iteration 100 \
--lambda-u 1 --T 1 --alpha 16 --mix-layers-set 7 9 12 \
--lrmain 0.000005 --lrlast 0.0005

2021-05-13 13:26:54.210367: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
GPU num:  1
Whether mix:  True
Mix layers sets:  [7, 9, 12]
We entered get_data
Read data successful (98007, 2) (42004, 2) n_labeled =  2400
                                                   0  1
0  RT @nasseratta5: The shopping Center before & ...  1
1  RT @CodeAud: #ISIS month of pain for civilians...  1
2  RT @AfarinMamosta: ISIS terrorists sent to hel...  1
3   #isis #islam #bombing pic.twitter.com/b664DSchOm  1
4  VERY BIG! #BreakingNews #ISIS-linked #Aamaq ne...  0
[1 1 1]
['RT @nasseratta5: The shopping Center before & after Isis suicide car bomb that killed more than 140 people in #Baghdad, #Iraq https://t.co/â\x80¦'
 'RT @CodeAud: #ISIS month of pain for civilians claims 830 lives in just 4 weeks of Ramadan. http://www.dailymail.co.uk/news/article-3673721/Islamic-State-s-four-weeks-pain-infidels-claim-800-lives-Huge-death-toll-attac